package com.interviewflow.notification.entity;

public enum NotificationType {
    OPPORTUNITY_CREATED,
    OPPORTUNITY_APPLIED,
    ASSESSMENT_RECEIVED,
    ASSESSMENT_COMPLETED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_COMPLETED,
    OFFER_RECEIVED,
    OFFER_ACCEPTED,
    OPPORTUNITY_REJECTED,
    OFFER_DECLINED,
    OPPORTUNITY_WITHDRAWN
}

